import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { readBrain } from "../make-workspace/read";
import { readToolbox, removeMcpEntry, upsertMcp, writeToolbox } from "./catalog";
import { findSecrets } from "./secrets";
import type { McpEntry } from "./types";

export interface InstallMcpInput {
  name: string;
  scope: "workspace" | "repo";
  repos: string[]; // for scope=repo
  description: string;
  config: unknown; // the harness MCP server definition (keep secret-free: use env refs)
  allowSecrets?: boolean; // escape hatch for the rare intentional literal
}

export interface InstallMcpRow {
  target: string; // "workspace" or a repo name
  status: "configured" | "repo-missing" | "unknown-repo";
}

export type InstallMcpResult =
  | { ok: true; rows: InstallMcpRow[] }
  | { ok: false; error: string };

// Merge one server into an .mcp.json file (Claude Code project MCP config),
// preserving any other servers already there.
async function mergeMcpJson(dir: string, name: string, config: unknown): Promise<void> {
  const path = join(dir, ".mcp.json");
  let doc: { mcpServers?: Record<string, unknown> } = {};
  try {
    const parsed = JSON.parse(await readFile(path, "utf8"));
    if (parsed && typeof parsed === "object") doc = parsed;
  } catch {
    // missing or malformed → start fresh
  }
  doc.mcpServers = { ...(doc.mcpServers ?? {}), [name]: config };
  await mkdir(dir, { recursive: true });
  await writeFile(path, `${JSON.stringify(doc, null, 2)}\n`, "utf8");
}

// Configures an MCP server at the workspace level (shared by the coordinator
// and every dispatched specialist subagent) or per-repo, and records it in the
// catalog so it survives publishing (regenerated by `aipe rehydrate`).
export async function installMcp(workspaceDir: string, input: InstallMcpInput): Promise<InstallMcpResult> {
  const brain = await readBrain(workspaceDir);
  if (!brain.ok) return { ok: false, error: brain.error };

  if (!input.allowSecrets) {
    const secrets = findSecrets(input.config);
    if (secrets.length > 0) {
      return {
        ok: false,
        error: `literal secret(s) in config at: ${secrets.join(", ")} — use env references like "\${VAR}", or pass --allow-secrets to override`,
      };
    }
  }

  const pathByRepo = new Map(brain.brain.repos.map((r) => [r.name, r.path]));

  const rows: InstallMcpRow[] = [];
  if (input.scope === "workspace") {
    await mergeMcpJson(workspaceDir, input.name, input.config);
    rows.push({ target: "workspace", status: "configured" });
  } else {
    for (const repoName of input.repos) {
      const repoPath = pathByRepo.get(repoName);
      if (!repoPath) {
        rows.push({ target: repoName, status: "unknown-repo" });
        continue;
      }
      const repoAbs = join(workspaceDir, repoPath);
      try {
        await mergeMcpJson(repoAbs, input.name, input.config);
        rows.push({ target: repoName, status: "configured" });
      } catch {
        rows.push({ target: repoName, status: "repo-missing" });
      }
    }
  }

  const entry: McpEntry = {
    name: input.name,
    scope: input.scope,
    repos: input.scope === "repo" ? input.repos : [],
    description: input.description,
    config: input.config,
  };
  await writeToolbox(workspaceDir, upsertMcp(await readToolbox(workspaceDir), entry));

  return { ok: true, rows };
}

// Remove one server from an .mcp.json, preserving every other server. Returns
// whether the server was actually present.
async function unmergeMcpJson(dir: string, name: string): Promise<boolean> {
  const path = join(dir, ".mcp.json");
  try {
    const parsed = JSON.parse(await readFile(path, "utf8"));
    if (parsed && typeof parsed === "object" && parsed.mcpServers && name in parsed.mcpServers) {
      delete parsed.mcpServers[name];
      await writeFile(path, `${JSON.stringify(parsed, null, 2)}\n`, "utf8");
      return true;
    }
  } catch {
    // missing or malformed → nothing to remove
  }
  return false;
}

export interface RemoveMcpRow {
  target: string; // "workspace" or a repo name
  status: "removed" | "not-present";
}

export type RemoveMcpResult =
  | { ok: true; name: string; rows: RemoveMcpRow[] }
  | { ok: false; error: string };

// Uninstalls an MCP server: drops it from the catalog and from the relevant
// .mcp.json (workspace or per-repo), leaving other servers intact. Refuses with
// not-found if the server isn't in the catalog.
export async function removeMcp(workspaceDir: string, name: string): Promise<RemoveMcpResult> {
  const toolbox = await readToolbox(workspaceDir);
  const entry = toolbox.mcps.find((m) => m.name.toLowerCase() === name.toLowerCase());
  if (!entry) return { ok: false, error: `not-found mcp "${name}"` };

  const brain = await readBrain(workspaceDir);
  const pathByRepo = new Map(brain.ok ? brain.brain.repos.map((r) => [r.name, r.path]) : []);

  const rows: RemoveMcpRow[] = [];
  if (entry.scope === "workspace") {
    const removed = await unmergeMcpJson(workspaceDir, entry.name);
    rows.push({ target: "workspace", status: removed ? "removed" : "not-present" });
  } else {
    for (const repoName of entry.repos) {
      const repoPath = pathByRepo.get(repoName);
      if (!repoPath) {
        rows.push({ target: repoName, status: "not-present" });
        continue;
      }
      const removed = await unmergeMcpJson(join(workspaceDir, repoPath), entry.name);
      rows.push({ target: repoName, status: removed ? "removed" : "not-present" });
    }
  }

  await writeToolbox(workspaceDir, removeMcpEntry(toolbox, entry.name).toolbox);
  return { ok: true, name: entry.name, rows };
}
