#!/usr/bin/env bun
// Regenerates src/toolbox/spec-kit-assets.ts from kits/spec-kit/vendor/**.
// Run after re-vendoring Spec Kit (fetching newer template/command/script files
// from github/spec-kit). Embedding them means `aipe skill add spec-kit`
// materializes a working setup with no uv/Python/network on the user's machine.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const VENDOR = join(ROOT, "kits", "spec-kit", "vendor");
const OUT = join(ROOT, "src", "toolbox", "spec-kit-assets.ts");

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(p)));
    else out.push(p);
  }
  return out;
}

const files = (await walk(VENDOR)).sort();
const entries = await Promise.all(
  files.map(async (f) => {
    const rel = relative(VENDOR, f).split("\\").join("/");
    return `  ${JSON.stringify(rel)}: ${JSON.stringify(await readFile(f, "utf8"))},`;
  }),
);
const body =
  `// AUTO-GENERATED by scripts/vendor-spec-kit.ts — do not edit by hand.\n` +
  `// Vendored GitHub Spec Kit source (MIT — github/spec-kit), embedded so\n` +
  `// \`aipe skill add spec-kit\` materializes it with no uv/Python/network.\n` +
  `export const SPEC_KIT_FILES: Record<string, string> = {\n${entries.join("\n")}\n};\n`;
await writeFile(OUT, body, "utf8");
console.log(`wrote ${OUT} with ${files.length} files`);
