import { renderGraphYaml } from "../relationship/render";
import type { GraphNode, MergedEdge } from "../relationship/types";
import type { HandoffRepoReport, ManifestEntry } from "./types";

export interface RenderInput {
  contextName: string;
  generatedAt: string;
  manifest: ManifestEntry[];
  reports: HandoffRepoReport[];
  nodes: GraphNode[];
  edges: MergedEdge[];
}

export function renderClaudeMd(input: RenderInput): string {
  const { contextName, generatedAt, manifest, reports, nodes, edges } = input;
  const reportByName = new Map(reports.map((r) => [r.repo, r]));
  const okEntries = manifest.filter((m) => m.status === "ok");
  const withReport = okEntries.filter((m) => reportByName.has(m.name));
  const failedEntries = manifest.filter((m) => m.status === "error");
  const missingReport = okEntries.filter((m) => !reportByName.has(m.name));

  const lines: string[] = [];
  lines.push(`# Context Handoff — ${contextName}`, "");
  lines.push(
    `> Generated by \`aipe handoff\` on ${generatedAt}. This file gives Claude (or any compatible harness) the full map of these repositories and how they relate — there is no need to ask the user about this.`,
    "",
  );

  lines.push("## Setup", "", "Clone these repositories as sibling folders of this file:", "");
  const withUrl = withReport.filter((m) => m.url !== undefined);
  if (withUrl.length > 0) {
    lines.push("```bash");
    for (const m of withUrl) lines.push(`git clone ${m.url}`);
    lines.push("```", "");
  }
  const withoutUrl = withReport.filter((m) => m.url === undefined);
  for (const m of withoutUrl) {
    lines.push(`> \`${m.name}\` has no known remote — copy that folder in manually before opening Claude Code here.`);
  }
  if (withoutUrl.length > 0) lines.push("");

  lines.push("## Repositories", "", "| Repo | Local path | Purpose | Stack |", "|------|-----------|---------|-------|");
  for (const m of withReport) {
    const report = reportByName.get(m.name);
    const purpose = report?.purpose ?? "";
    const stack = report?.stack.join(", ") ?? "";
    lines.push(`| ${m.name} | ./${m.name} | ${purpose} | ${stack} |`);
  }
  lines.push("");

  lines.push("## Relations", "");
  if (edges.length === 0) {
    lines.push("_No relations discovered._", "");
  } else {
    for (const edge of edges) {
      lines.push(`- **${edge.from} → ${edge.to}** (\`${edge.type}\`)`);
      for (const p of edge.perspectives) {
        lines.push(`  - ${p.detail} (\`${p.evidence}\`)`);
      }
    }
    lines.push("");
  }

  const pending = [
    ...failedEntries.map((m) => ({ name: m.name, reason: m.message ?? "clone failed" })),
    ...missingReport.map((m) => ({ name: m.name, reason: "no agent report" })),
  ];
  if (pending.length > 0) {
    lines.push("## Pending", "");
    for (const p of pending) {
      lines.push(
        `- \`${p.name}\`: ${p.reason} — retry with \`aipe handoff clone --repo <url-or-path> --out <dir>\` then \`aipe handoff render --out <dir> --name "${contextName}"\`.`,
      );
    }
    lines.push("");
  }

  lines.push(
    "<details>",
    "<summary>Structured graph (for agents)</summary>",
    "",
    "```yaml",
    renderGraphYaml(nodes, edges).trimEnd(),
    "```",
    "",
    "</details>",
    "",
  );

  return lines.join("\n");
}
